//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.IO;
using System.Windows;
namespace Exam5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int ProductID { get; set; }
        public string Article { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public string Manufacturer { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Status { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public string ImagePath
        {
            get
            {
                try
                {
                    // 1. Проверяем, есть ли фото в базе
                    if (string.IsNullOrEmpty(this.Photo))
                    {
                        // Если фото нет в БД - возвращаем заглушку
                        return Path.Combine(Directory.GetCurrentDirectory(), "Images", "logo.png");
                    }

                    // 2. Проверяем расширение файла
                    string photoFileName = this.Photo.Trim(); // Убираем пробелы

                    // Если в названии нет точки, добавляем .jpg по умолчанию
                    if (!photoFileName.Contains("."))
                    {
                        photoFileName += ".jpg";
                    }

                    // 3. Собираем путь
                    string imagePath = Path.Combine(Directory.GetCurrentDirectory(), "Images", photoFileName);

                    // 4. Проверяем существует ли файл
                    if (File.Exists(imagePath))
                    {
                        return imagePath;
                    }
                    else
                    {
                        // Логируем, если файл не найден (для отладки)
                        Console.WriteLine($"Файл не найден: {imagePath}");

                        // Пробуем найти по ProductID
                        string idImagePath = Path.Combine(Directory.GetCurrentDirectory(), "Images", $"{this.ProductID}.jpg");
                        if (File.Exists(idImagePath))
                        {
                            return idImagePath;
                        }

                        // Возвращаем заглушку
                        return Path.Combine(Directory.GetCurrentDirectory(), "Images", "logo.png");
                    }
                }
                catch (Exception ex)
                {
                    // Логируем ошибку, чтобы понять что не так
                    Console.WriteLine($"Ошибка в ImagePath для товара {this.ProductID}: {ex.Message}");

                    // Возвращаем заглушку при любой ошибке
                    return Path.Combine(Directory.GetCurrentDirectory(), "Images", "logo.png");
                }
            }
        }
    }

}
